apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: java-spring-boot-maven
  annotations:
    github.com/project-slug: knowmad-mood/java-spring-boot-maven
spec:
  type: other
  lifecycle: unknown
  owner: knowmad-mood
